### ISSUE TITLE
RoR group project  - Set up  Kanban board

### ISSUE THREAD

**Issue by Donard97** [Donard97/recipe-app#11]
_**We opened this issue for you to review our board if it is as requested.**_

In this activity, we prepared a Kanban Board with a Github project from scratch. 📑 
Here is the link of our board: https://github.com/Donard97/recipe-app/projects/1
Our team has 2 members: @Donard97 & @Kossi-stack 💪 💯 

### Project requirements that are done:

- Opened the GitHub project on the recipe-app repo ☑️ 
- Created tasks on your Kanban board based on the project requirements ☑️ 
- Each task has a separate card ☑️ 
- All cards on your Kanban board have assignees. ☑️ 

<hr>

_Feel free to review 👀 my project and let me know if there are any essential changes 💪_

**Comment by dasileker** [comment]
## **Hi @Donard97,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
